using System;

namespace Ecr.Module.Services.Ingenico.GmpIngenico
{
    class ErrorClass
    {

       public static string DisplayErrorMessage(uint errorCode)
        {
            string result = "";
            switch (errorCode)
            {
                case Defines.TRAN_RESULT_OK: result = DescDefines.TRAN_RESULT_OK; break;
                case Defines.TRAN_RESULT_NOT_ALLOWED: result = DescDefines.TRAN_RESULT_NOT_ALLOWED; break;
                case Defines.TRAN_RESULT_TIMEOUT: result = DescDefines.TRAN_RESULT_TIMEOUT; break;
                case Defines.TRAN_RESULT_USER_ABORT: result = DescDefines.TRAN_RESULT_USER_ABORT; break;
                case Defines.TRAN_RESULT_EKU_PROBLEM: result = DescDefines.TRAN_RESULT_EKU_PROBLEM; break;
                case Defines.TRAN_RESULT_CONTINUE: result = DescDefines.TRAN_RESULT_CONTINUE; break;
                case Defines.TRAN_RESULT_NO_PAPER: result = DescDefines.TRAN_RESULT_NO_PAPER; break;
                case Defines.APP_ERR_FISCAL_EXCHANGE_RATES_NOT_FOUND: result = DescDefines.APP_ERR_FISCAL_EXCHANGE_RATES_NOT_FOUND; break;
                case Defines.APP_ERR_FISCAL_ALREADY_CANCELED_ITEM: result = DescDefines.APP_ERR_FISCAL_ALREADY_CANCELED_ITEM; break;
                case Defines.APP_ERR_FISCAL_INVALID_DISCOUNT_RATE: result = DescDefines.APP_ERR_FISCAL_INVALID_DISCOUNT_RATE; break;
                case Defines.APP_ERR_FISCAL_DISCOUNT_RATE_NOT_SET: result = DescDefines.APP_ERR_FISCAL_DISCOUNT_RATE_NOT_SET; break;
                case Defines.APP_ERR_FISCAL_INVALID_INCREASE_RATE: result = DescDefines.APP_ERR_FISCAL_INVALID_INCREASE_RATE; break;
                case Defines.APP_ERR_FISCAL_INCREASE_RATE_NOT_SET: result = DescDefines.APP_ERR_FISCAL_INCREASE_RATE_NOT_SET; break;
                case Defines.APP_ERR_FISCAL_DISCOUNT_ALREADY_DONE: result = DescDefines.APP_ERR_FISCAL_DISCOUNT_ALREADY_DONE; break;
                case Defines.APP_ERR_FISCAL_INCREASE_ALREADY_DONE: result = DescDefines.APP_ERR_FISCAL_INCREASE_ALREADY_DONE; break;
                case Defines.APP_ERR_FISCAL_NO_PRETOTAL: result = DescDefines.APP_ERR_FISCAL_NO_PRETOTAL; break;
                case Defines.APP_ERR_FISCAL_INVALID_ENTRY: result = DescDefines.APP_ERR_FISCAL_INVALID_ENTRY; break;
                case Defines.APP_ERR_FISCAL_KDV_RATE_NOT_FOUND: result = DescDefines.APP_ERR_FISCAL_KDV_RATE_NOT_FOUND; break;
                case Defines.APP_ERR_FISCAL_TICKET_LIMIT_EXCEED: result = DescDefines.APP_ERR_FISCAL_TICKET_LIMIT_EXCEED; break;
                case Defines.APP_ERR_FISCAL_SALE_ITEM_LIMIT_EXCEED: result = DescDefines.APP_ERR_FISCAL_SALE_ITEM_LIMIT_EXCEED; break;
                case Defines.APP_ERR_FISCAL_CASH_ENTRY_LIMIT_EXCED: result = DescDefines.APP_ERR_FISCAL_CASH_ENTRY_LIMIT_EXCED; break;
                case Defines.APP_ERR_FISCAL_INVALID_CURRENCY: result = DescDefines.APP_ERR_FISCAL_INVALID_CURRENCY; break;
                case Defines.APP_ERR_NOT_ALLOWED_BEFORE_GIB_CONNECTION: result = DescDefines.APP_ERR_NOT_ALLOWED_BEFORE_GIB_CONNECTION; break;
                case Defines.APP_ERR_KISIM_FIYAT_LIMITI_ASILAMAZ: result = DescDefines.APP_ERR_KISIM_FIYAT_LIMITI_ASILAMAZ; break;
                case Defines.APP_ERR_FISCAL_DEPARTMENT_ENTRY_INCOMPLETE: result = DescDefines.APP_ERR_FISCAL_DEPARTMENT_ENTRY_INCOMPLETE; break;
                case Defines.APP_ERR_FISCAL_EXCHANGE_RATE_NOT_FOUND: result = DescDefines.APP_ERR_FISCAL_EXCHANGE_RATE_NOT_FOUND; break;
                case Defines.APP_ERR_APL_CRC_ERROR: result = DescDefines.APP_ERR_APL_CRC_ERROR; break;
                case Defines.APP_ERR_APL_VERS_ERROR: result = DescDefines.APP_ERR_APL_VERS_ERROR; break;
                case Defines.APP_ERR_APL_COMPLETE_PAYMENT: result = DescDefines.APP_ERR_APL_COMPLETE_PAYMENT; break;
                case Defines.APP_ERR_APL_CREDIT_CANNOT_BIGGER_THAN_REMAIN_AMOUNT: result = DescDefines.APP_ERR_APL_CREDIT_CANNOT_BIGGER_THAN_REMAIN_AMOUNT; break;
                case Defines.APP_ERR_APL_CREDIT_PAID_AMOUNT_MISSING: result = DescDefines.APP_ERR_APL_CREDIT_PAID_AMOUNT_MISSING; break;
                case Defines.APP_ERR_APL_CREDIT_PAID_ONLY_ONE_TIME_ALLOWED: result = DescDefines.APP_ERR_APL_CREDIT_PAID_ONLY_ONE_TIME_ALLOWED; break;
                case Defines.APP_ERR_FISCAL_INVALID_DATE_TIME: result = DescDefines.APP_ERR_FISCAL_INVALID_DATE_TIME; break;
                case Defines.APP_ERR_MAX_RECEIPT_COUNTER_REACHED: result = DescDefines.APP_ERR_MAX_RECEIPT_COUNTER_REACHED; break;
                case Defines.APP_ERR_APL_NO_PAPER: result = DescDefines.APP_ERR_APL_NO_PAPER; break;
                case Defines.APP_ERR_APL_PARAMETRE_NOT_FOUND: result = DescDefines.APP_ERR_APL_PARAMETRE_NOT_FOUND; break;
                case Defines.APP_ERR_EKU_SOFTWARE_VERSION: result = DescDefines.APP_ERR_EKU_SOFTWARE_VERSION; break;
                case Defines.APP_ERR_FISCAL_SOFTWARE_VERSION /*2030*/                : result = DescDefines.APP_ERR_FISCAL_SOFTWARE_VERSION /*2030*/    ; break;
                case Defines.APP_ERR_CIHAZ_GECICI_OLARAK_KAPATILDI: result = DescDefines.APP_ERR_CIHAZ_GECICI_OLARAK_KAPATILDI; break;
                case Defines.APP_ERR_CIHAZ_ACIL_MODA_ALINMIS: result = DescDefines.APP_ERR_CIHAZ_ACIL_MODA_ALINMIS; break;
                case Defines.APP_ERR_APL_DAILY_MEMORY_DELETED: result = DescDefines.APP_ERR_APL_DAILY_MEMORY_DELETED; break;
                case Defines.APP_ERR_APL_CUMULATIVE_COUNTER_FULL: result = DescDefines.APP_ERR_APL_CUMULATIVE_COUNTER_FULL; break;
                case Defines.APP_ERR_APL_OUT_OF_SERVICE: result = DescDefines.APP_ERR_APL_OUT_OF_SERVICE; break;
                case Defines.APP_ERR_APL_OUT_OF_SERVICE_WARNING: result = DescDefines.APP_ERR_APL_OUT_OF_SERVICE_WARNING; break;
                case Defines.APP_ERR_APL_FONT_FILE_LOAD: result = DescDefines.APP_ERR_APL_FONT_FILE_LOAD; break;
                case Defines.APP_ERR_APL_FONT_POLICY_NOT_FOUND: result = DescDefines.APP_ERR_APL_FONT_POLICY_NOT_FOUND; break;
                case Defines.APP_ERR_APL_CREDIT_PAY_AMOUNT_ZERO: result = DescDefines.APP_ERR_APL_CREDIT_PAY_AMOUNT_ZERO; break;
                case Defines.APP_ERR_APL_DB_ERROR /* 2040*/                          : result = DescDefines.APP_ERR_APL_DB_ERROR /* 2040*/              ; break;
                case Defines.APP_ERR_TICKET_SALE_ITEM_LIMIT_EXCEED: result = DescDefines.APP_ERR_TICKET_SALE_ITEM_LIMIT_EXCEED; break;
                case Defines.APP_ERR_APL_PIN_ERROR: result = DescDefines.APP_ERR_APL_PIN_ERROR; break;
                case Defines.APP_ERR_PAYMENT_APPL_MESSAGE: result = DescDefines.APP_ERR_PAYMENT_APPL_MESSAGE; break;
                case Defines.APP_ERR_APL_DB_DUBLICATE_RECORD: result = DescDefines.APP_ERR_APL_DB_DUBLICATE_RECORD; break;
                case Defines.APP_ERR_APL_TRANSACTION_CORRUPTED: result = DescDefines.APP_ERR_APL_TRANSACTION_CORRUPTED; break;
                case Defines.APP_ERR_APL_PAYMENT_MUST_COMPLETE: result = DescDefines.APP_ERR_APL_PAYMENT_MUST_COMPLETE; break;
                case Defines.APP_ERR_INVOICE_LIMIT_EXCEED: result = DescDefines.APP_ERR_INVOICE_LIMIT_EXCEED; break;
                case Defines.APP_ERR_TRANSACTION_NOT_SAVED: result = DescDefines.APP_ERR_TRANSACTION_NOT_SAVED; break;
                case Defines.APP_ERR_INVOICE_NO_ENTRY: result = DescDefines.APP_ERR_INVOICE_NO_ENTRY; break;
                case Defines.APP_ERR_INACTIVE_PERIPHERAL: result = DescDefines.APP_ERR_INACTIVE_PERIPHERAL; break;
                case Defines.APP_ERR_DEVICE_CLOSED: result = DescDefines.APP_ERR_DEVICE_CLOSED; break;
                case Defines.APP_ERR_TEST_REQUIRED: result = DescDefines.APP_ERR_TEST_REQUIRED; break;
                case Defines.APP_ERR_CASHIER_ENTRY_REQUIRED: result = DescDefines.APP_ERR_CASHIER_ENTRY_REQUIRED; break;
                case Defines.APP_ERR_FLIGHT_MODE: result = DescDefines.APP_ERR_FLIGHT_MODE; break;
                case Defines.APP_ERR_NO_PARAM: result = DescDefines.APP_ERR_NO_PARAM; break;
                case Defines.APP_ERR_NOT_FISCAL: result = DescDefines.APP_ERR_NOT_FISCAL; break;
                case Defines.APP_ERR_FISCAL_RECORD_NOT_AVAILABLE: result = DescDefines.APP_ERR_FISCAL_RECORD_NOT_AVAILABLE; break;
                case Defines.APP_ERR_CITIZEN_NUMBER_ENTRY: result = DescDefines.APP_ERR_CITIZEN_NUMBER_ENTRY; break;
                case Defines.APP_ERR_INVALID_USER_MODE: result = DescDefines.APP_ERR_INVALID_USER_MODE; break;
                case Defines.APP_ERR_PAYMENT_NOT_ALLOWED: result = DescDefines.APP_ERR_PAYMENT_NOT_ALLOWED; break;
                case Defines.APP_ERR_NO_CASH: result = DescDefines.APP_ERR_NO_CASH; break;
                case Defines.APP_ERR_PARAMETER_DW_ERROR_FOR_TEST: result = DescDefines.APP_ERR_PARAMETER_DW_ERROR_FOR_TEST; break;
                case Defines.APP_ERR_MAX_TRY_COUNTER_EXCEED: result = DescDefines.APP_ERR_MAX_TRY_COUNTER_EXCEED; break;
                case Defines.APP_ERR_NOT_ALLOWED: result = DescDefines.APP_ERR_NOT_ALLOWED; break;
                case Defines.APP_ERR_RESOURCE_PROBLEM: result = DescDefines.APP_ERR_RESOURCE_PROBLEM; break;
                case Defines.APP_ERR_ITEM_PRICE_NOT_EXISTS: result = DescDefines.APP_ERR_ITEM_PRICE_NOT_EXISTS; break;
                case Defines.APP_ERR_FIS_LIMITI_ASILAMAZ: result = DescDefines.APP_ERR_FIS_LIMITI_ASILAMAZ; break;
                case Defines.APP_ERR_NO_ITEM: result = DescDefines.APP_ERR_NO_ITEM; break;
                case Defines.APP_ERR_PAYMENT_FOUND: result = DescDefines.APP_ERR_PAYMENT_FOUND; break;
                case Defines.APP_ERR_MATRAHSIZ_FOUND: result = DescDefines.APP_ERR_MATRAHSIZ_FOUND; break;
                case Defines.APP_ERR_NOT_APPROVED: result = DescDefines.APP_ERR_NOT_APPROVED; break;
                case Defines.APP_ERR_ONLY_COUPON: result = DescDefines.APP_ERR_ONLY_COUPON; break;
                case Defines.APP_ERR_NO_AMOUNT: result = DescDefines.APP_ERR_NO_AMOUNT; break;
                case Defines.APP_ERR_CURRENCY_NOT_SUPPORTED: result = DescDefines.APP_ERR_CURRENCY_NOT_SUPPORTED; break;
                case Defines.APP_ERR_TICKET_TOTAL_CANNOT_BE_ZERO: result = DescDefines.APP_ERR_TICKET_TOTAL_CANNOT_BE_ZERO; break;
                case Defines.APP_ERR_INVOICE_NOT_ALLOWED: result = DescDefines.APP_ERR_INVOICE_NOT_ALLOWED; break;
                case Defines.APP_ERR_TICKET_HEADER_NOT_PRINTED: result = DescDefines.APP_ERR_TICKET_HEADER_NOT_PRINTED; break;
                case Defines.APP_ERR_TICKET_HEADER_ALREADY_PRINTED: result = DescDefines.APP_ERR_TICKET_HEADER_ALREADY_PRINTED; break;
                case Defines.APP_ERR_PLU_NOT_FOUND: result = DescDefines.APP_ERR_PLU_NOT_FOUND; break;
                case Defines.APP_ERR_ALREADY_DONE   /* 2080*/                        : result = DescDefines.APP_ERR_ALREADY_DONE    /* 2080*/           ; break;
                case Defines.APP_ERR_INVALID_PARAMETER_TAXINDEX: result = DescDefines.APP_ERR_INVALID_PARAMETER_TAXINDEX; break;
                case Defines.APP_ERR_INVALID_PARAMETER_TAXRATE: result = DescDefines.APP_ERR_INVALID_PARAMETER_TAXRATE; break;
                case Defines.APP_ERR_MISSING_PARAMETER: result = DescDefines.APP_ERR_MISSING_PARAMETER; break;
                case Defines.APP_ERR_MISMATCH_PARAMETER: result = DescDefines.APP_ERR_MISMATCH_PARAMETER; break;
                case Defines.APP_ERR_PAYMENT_NOT_SUCCESSFUL_AND_NO_MORE_ERROR_CODE: result = DescDefines.APP_ERR_PAYMENT_NOT_SUCCESSFUL_AND_NO_MORE_ERROR_CODE; break;
                case Defines.APP_ERR_PAYMENT_NOT_SUCCESSFUL_AND_MORE_ERROR_CODE: result = DescDefines.APP_ERR_PAYMENT_NOT_SUCCESSFUL_AND_MORE_ERROR_CODE; break;
                case Defines.APP_ERR_INVALID_PAYMENT_TYPE: result = DescDefines.APP_ERR_INVALID_PAYMENT_TYPE; break;
                case Defines.APP_ERR_VAS_NOT_AVAILABLE: result = DescDefines.APP_ERR_VAS_NOT_AVAILABLE; break;
                case Defines.APP_ERR_INVALID_CAR_IDENTIFICATION: result = DescDefines.APP_ERR_INVALID_CAR_IDENTIFICATION; break;
                case Defines.APP_ERR_CHECK_IP_ADDRES_FORMAT /*= 2100 */              : result = DescDefines.APP_ERR_CHECK_IP_ADDRES_FORMAT /*= 2100 */            ; break;
                case Defines.APP_ERR_WRONG_SERVICE_CARD_PIN: result = DescDefines.APP_ERR_WRONG_SERVICE_CARD_PIN; break;
                case Defines.APP_ERR_UNDEFINED_COM_INTERFACE: result = DescDefines.APP_ERR_UNDEFINED_COM_INTERFACE; break;
                case Defines.APP_ERR_BASE_NOT_FOUND: result = DescDefines.APP_ERR_BASE_NOT_FOUND; break;
                case Defines.APP_ERR_ETHERNET_MODUL_CALISMIYOR: result = DescDefines.APP_ERR_ETHERNET_MODUL_CALISMIYOR; break;
                case Defines.APP_ERR_ETHERNET_NOT_PLUGGED: result = DescDefines.APP_ERR_ETHERNET_NOT_PLUGGED; break;
                case Defines.APP_ERR_ETHERNET_BASE_NOT_READY: result = DescDefines.APP_ERR_ETHERNET_BASE_NOT_READY; break;
                case Defines.APP_ERR_ETHERNET_OUT_OF_BASE: result = DescDefines.APP_ERR_ETHERNET_OUT_OF_BASE; break;
                case Defines.APP_ERR_GPRS_ERROR_NO_SIM: result = DescDefines.APP_ERR_GPRS_ERROR_NO_SIM; break;
                case Defines.APP_ERR_GPRS_APN: result = DescDefines.APP_ERR_GPRS_APN; break;
                case Defines.APP_ERR_GPRS_BAD_PIN: result = DescDefines.APP_ERR_GPRS_BAD_PIN; break;
                case Defines.APP_ERR_GPRS_SIM_LOCK: result = DescDefines.APP_ERR_GPRS_SIM_LOCK; break;
                case Defines.APP_ERR_GPRS_NO_SIGNAL: result = DescDefines.APP_ERR_GPRS_NO_SIGNAL; break;
                case Defines.APP_ERR_GPRS_DISCONNCTED: result = DescDefines.APP_ERR_GPRS_DISCONNCTED; break;
                case Defines.APP_ERR_GPRS_UNDEFINED: result = DescDefines.APP_ERR_GPRS_UNDEFINED; break;
                case Defines.APP_ERR_SSL_PROFILE: result = DescDefines.APP_ERR_SSL_PROFILE; break;
                case Defines.APP_ERR_WRONG_SERVICE_CARD: result = DescDefines.APP_ERR_WRONG_SERVICE_CARD; break;
                case Defines.APP_ERR_COMMUNICATION_CHANNEL_NOT_DEFINED: result = DescDefines.APP_ERR_COMMUNICATION_CHANNEL_NOT_DEFINED; break;
                case Defines.APP_ERR_GIB_ROOT_CERT_NOT_FOUND: result = DescDefines.APP_ERR_GIB_ROOT_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_GIB_SUB_ROOT_CERT_NOT_FOUND: result = DescDefines.APP_ERR_GIB_SUB_ROOT_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_TSM_ROOT_CERT_NOT_FOUND: result = DescDefines.APP_ERR_TSM_ROOT_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_TSM_SUB_ROOT_CERT_NOT_FOUND: result = DescDefines.APP_ERR_TSM_SUB_ROOT_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_OKTEM_CERT_NOT_FOUND: result = DescDefines.APP_ERR_OKTEM_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_GIB_SIGN_CERT_NOT_FOUND: result = DescDefines.APP_ERR_GIB_SIGN_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_GIB_SIFRE_CERT_NOT_FOUND: result = DescDefines.APP_ERR_GIB_SIFRE_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_TSM_SIGN_CERT_NOT_FOUND: result = DescDefines.APP_ERR_TSM_SIGN_CERT_NOT_FOUND; break;
                case Defines.APP_ERR_PACK_GIB: result = DescDefines.APP_ERR_PACK_GIB; break;
                case Defines.APP_ERR_GIB_CERT: result = DescDefines.APP_ERR_GIB_CERT; break;
                case Defines.APP_ERR_DATABASE_SILINMIS: result = DescDefines.APP_ERR_DATABASE_SILINMIS; break;
                case Defines.APP_ERR_FILE_COPY: result = DescDefines.APP_ERR_FILE_COPY; break;
                case Defines.APP_ERR_FILE_OPEN: result = DescDefines.APP_ERR_FILE_OPEN; break;
                case Defines.APP_ERR_FILE_READ: result = DescDefines.APP_ERR_FILE_READ; break;
                case Defines.APP_ERR_FILE_WRITE: result = DescDefines.APP_ERR_FILE_WRITE; break;
                case Defines.APP_ERR_BUFFER_MALLOC: result = DescDefines.APP_ERR_BUFFER_MALLOC; break;
                case Defines.APP_ERR_FILE_SEEK: result = DescDefines.APP_ERR_FILE_SEEK; break;
                case Defines.APP_ERR_FILE_EOF: result = DescDefines.APP_ERR_FILE_EOF; break;
                case Defines.APP_ERR_GMP_PROTOCOL: result = DescDefines.APP_ERR_GMP_PROTOCOL; break;
                case Defines.APP_ERR_GMP_VERIFICATION: result = DescDefines.APP_ERR_GMP_VERIFICATION; break;
                case Defines.APP_ERR_GMP_LRC: result = DescDefines.APP_ERR_GMP_LRC; break;
                case Defines.APP_ERR_COMPONENT_ABSENT: result = DescDefines.APP_ERR_COMPONENT_ABSENT; break;
                case Defines.APP_ERR_SQL: result = DescDefines.APP_ERR_SQL; break;
                case Defines.APP_ERR_GMP_RESPONSE_CODE_ERROR: result = DescDefines.APP_ERR_GMP_RESPONSE_CODE_ERROR; break;
                case Defines.APP_ERR_FRAM_Z_REPORT_UPDATE: result = DescDefines.APP_ERR_FRAM_Z_REPORT_UPDATE; break;
                case Defines.APP_ERR_DAILY_WRITE: result = DescDefines.APP_ERR_DAILY_WRITE; break;
                case Defines.APP_ERR_FISCAL_CUMULATIVE_WRITE: result = DescDefines.APP_ERR_FISCAL_CUMULATIVE_WRITE; break;
                case Defines.APP_ERR_GMP_PROTOCOL_CANNOT_RECEIVED_FULL_MESSAGE: result = DescDefines.APP_ERR_GMP_PROTOCOL_CANNOT_RECEIVED_FULL_MESSAGE; break;
                case Defines.APP_ERR_GMP_PROTOCOL_TPDU_NOT_RECEIVED: result = DescDefines.APP_ERR_GMP_PROTOCOL_TPDU_NOT_RECEIVED; break;
                case Defines.APP_ERR_GMP_AUTO_FICAL_FAILED: result = DescDefines.APP_ERR_GMP_AUTO_FICAL_FAILED; break;
                case Defines.APP_ERR_GMP_EFTPOS_BAGLANTISI_BULUNAMADI: result = DescDefines.APP_ERR_GMP_EFTPOS_BAGLANTISI_BULUNAMADI; break;
                case Defines.APP_ERR_GMP_GIB_KEY_IMZA_VERIFICATION: result = DescDefines.APP_ERR_GMP_GIB_KEY_IMZA_VERIFICATION; break;
                case Defines.APP_ERR_GMP_GIB_SHA2_IDENTIFIER: result = DescDefines.APP_ERR_GMP_GIB_SHA2_IDENTIFIER; break;
                case Defines.APP_ERR_GMP_MISSING_GROUP: result = DescDefines.APP_ERR_GMP_MISSING_GROUP; break;
                case Defines.APP_ERR_GMP_BUFFER_ERROR: result = DescDefines.APP_ERR_GMP_BUFFER_ERROR; break;
                case Defines.APP_ERR_GMP_PADDING_ERROR: result = DescDefines.APP_ERR_GMP_PADDING_ERROR; break;
                case Defines.APP_ERR_GMP_TREK_TRAK_MISMATCH: result = DescDefines.APP_ERR_GMP_TREK_TRAK_MISMATCH; break;
                case Defines.APP_ERR_GMP_TSM_KEY_IMZA_VERIFICATION: result = DescDefines.APP_ERR_GMP_TSM_KEY_IMZA_VERIFICATION; break;
                case Defines.APP_ERR_GMP_NEGATIVE_TRANSACTION: result = DescDefines.APP_ERR_GMP_NEGATIVE_TRANSACTION; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_OKC_MODEL: result = DescDefines.APP_ERR_GMP3_UNDEFINED_OKC_MODEL; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_OKC_VENDOR: result = DescDefines.APP_ERR_GMP3_UNDEFINED_OKC_VENDOR; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_OKC_SICILNO: result = DescDefines.APP_ERR_GMP3_UNDEFINED_OKC_SICILNO; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_CIHAZ_MODEL: result = DescDefines.APP_ERR_GMP3_UNDEFINED_CIHAZ_MODEL; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_CIHAZ_VENDOR: result = DescDefines.APP_ERR_GMP3_UNDEFINED_CIHAZ_VENDOR; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_CIHAZ_SERINO: result = DescDefines.APP_ERR_GMP3_UNDEFINED_CIHAZ_SERINO; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_MSG_TYPE: result = DescDefines.APP_ERR_GMP3_UNDEFINED_MSG_TYPE; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_MISSING_PARAMETER: result = DescDefines.APP_ERR_GMP3_UNDEFINED_MISSING_PARAMETER; break;
                case Defines.APP_ERR_GMP3_INVALID_SEQUENCE_NUMBER: result = DescDefines.APP_ERR_GMP3_INVALID_SEQUENCE_NUMBER; break;
                case Defines.APP_ERR_GMP3_INVALID_DATE_TIME: result = DescDefines.APP_ERR_GMP3_INVALID_DATE_TIME; break;
                case Defines.APP_ERR_GMP3_MISSING_TDES_KEY: result = DescDefines.APP_ERR_GMP3_MISSING_TDES_KEY; break;
                case Defines.APP_ERR_GMP3_INVALID_KCV: result = DescDefines.APP_ERR_GMP3_INVALID_KCV; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_STATUS: result = DescDefines.APP_ERR_GMP3_UNDEFINED_STATUS; break;
                case Defines.APP_ERR_GMP3_TIMEOUT: result = DescDefines.APP_ERR_GMP3_TIMEOUT; break;
                case Defines.APP_ERR_GMP3_CERTIFICATE: result = DescDefines.APP_ERR_GMP3_CERTIFICATE; break;
                case Defines.APP_ERR_GMP3_VERIFY: result = DescDefines.APP_ERR_GMP3_VERIFY; break;
                case Defines.APP_ERR_GMP3_INVALID_HANDLE: result = DescDefines.APP_ERR_GMP3_INVALID_HANDLE; break;
                case Defines.APP_ERR_GMP3_CRC: result = DescDefines.APP_ERR_GMP3_CRC; break;
                case Defines.APP_ERR_GMP3_LEN: result = DescDefines.APP_ERR_GMP3_LEN; break;
                case Defines.APP_ERR_GMP3_STX: result = DescDefines.APP_ERR_GMP3_STX; break;
                case Defines.APP_ERR_GMP3_ETX: result = DescDefines.APP_ERR_GMP3_ETX; break;
                case Defines.APP_ERR_GMP3_NACK: result = DescDefines.APP_ERR_GMP3_NACK; break;
                case Defines.APP_ERR_GMP3_ACK: result = DescDefines.APP_ERR_GMP3_ACK; break;
                case Defines.APP_ERR_GMP3_RECEIVE: result = DescDefines.APP_ERR_GMP3_RECEIVE; break;
                case Defines.APP_ERR_GMP3_SEND: result = DescDefines.APP_ERR_GMP3_SEND; break;
                case Defines.APP_ERR_GMP3_PARSE: result = DescDefines.APP_ERR_GMP3_PARSE; break;
                case Defines.APP_ERR_GMP3_USER_BREAK: result = DescDefines.APP_ERR_GMP3_USER_BREAK; break;
                case Defines.APP_ERR_GMP3_PROTOCOL: result = DescDefines.APP_ERR_GMP3_PROTOCOL; break;
                case Defines.APP_ERR_GMP3_PAIRING_REQUIRED: result = DescDefines.APP_ERR_GMP3_PAIRING_REQUIRED; break;
                case Defines.APP_ERR_GMP3_UNKNOWN_DEVICE: result = DescDefines.APP_ERR_GMP3_UNKNOWN_DEVICE; break;
                case Defines.APP_ERR_GMP3_VERSION_MISMATCH: result = DescDefines.APP_ERR_GMP3_VERSION_MISMATCH; break;
                case Defines.APP_ERR_GMP3_NO_PRIME_NUMBER: result = DescDefines.APP_ERR_GMP3_NO_PRIME_NUMBER; break;
                case Defines.APP_ERR_GMP3_PERMISSION: result = DescDefines.APP_ERR_GMP3_PERMISSION; break;
                case Defines.APP_ERR_GMP3_INCORRECT_DEVICE: result = DescDefines.APP_ERR_GMP3_INCORRECT_DEVICE; break;
                case Defines.APP_ERR_GMP3_MEMORY_READ_ERROR: result = DescDefines.APP_ERR_GMP3_MEMORY_READ_ERROR; break;
                case Defines.APP_ERR_GMP3_MEMORY_WRITE_ERROR: result = DescDefines.APP_ERR_GMP3_MEMORY_WRITE_ERROR; break;
                case Defines.APP_ERR_GMP3_MEMORY_ERASE_ERROR: result = DescDefines.APP_ERR_GMP3_MEMORY_ERASE_ERROR; break;
                case Defines.APP_ERR_GMP3_APP_CHECKSUM_MISMATCH: result = DescDefines.APP_ERR_GMP3_APP_CHECKSUM_MISMATCH; break;
                case Defines.APP_ERR_GMP3_APP_DATE_EXPIRED: result = DescDefines.APP_ERR_GMP3_APP_DATE_EXPIRED; break;
                case Defines.APP_ERR_GMP3_TCP_RECEIVE_ERROR: result = DescDefines.APP_ERR_GMP3_TCP_RECEIVE_ERROR; break;
                case Defines.APP_ERR_GMP3_NO_HANDLE: result = DescDefines.APP_ERR_GMP3_NO_HANDLE; break;
                case Defines.APP_ERR_GMP3_PAYMENT_KDV_NOT_AVAILABLE: result = DescDefines.APP_ERR_GMP3_PAYMENT_KDV_NOT_AVAILABLE; break;
                case Defines.APP_ERR_GMP3_ITEM_NOT_AVAILABLE: result = DescDefines.APP_ERR_GMP3_ITEM_NOT_AVAILABLE; break;
                case Defines.APP_ERR_GMP3_OKC_KISIM_UNKNOWN: result = DescDefines.APP_ERR_GMP3_OKC_KISIM_UNKNOWN; break;
                case Defines.APP_ERR_GMP3_DOVIZ_UNKNOWN: result = DescDefines.APP_ERR_GMP3_DOVIZ_UNKNOWN; break;
                case Defines.APP_ERR_GMP3_KASIYER_UNKNOWN: result = DescDefines.APP_ERR_GMP3_KASIYER_UNKNOWN; break;
                case Defines.APP_ERR_GMP3_FUNC_OKC_PARAMETRE: result = DescDefines.APP_ERR_GMP3_FUNC_OKC_PARAMETRE; break;
                case Defines.APP_ERR_GMP3_FATURA_ODEME_PARAMETRE: result = DescDefines.APP_ERR_GMP3_FATURA_ODEME_PARAMETRE; break;
                case Defines.APP_ERR_GMP3_Z_RAPOR: result = DescDefines.APP_ERR_GMP3_Z_RAPOR; break;
                case Defines.APP_ERR_GMP3_X_RAPOR: result = DescDefines.APP_ERR_GMP3_X_RAPOR; break;
                case Defines.APP_ERR_GMP3_BATTERY_LEVEL: result = DescDefines.APP_ERR_GMP3_BATTERY_LEVEL; break;
                case Defines.APP_ERR_GMP3_EKU_RAPOR_TYPE: result = DescDefines.APP_ERR_GMP3_EKU_RAPOR_TYPE; break;
                case Defines.APP_ERR_GMP3_EKU_STATE: result = DescDefines.APP_ERR_GMP3_EKU_STATE; break;
                case Defines.APP_ERR_GMP3_ECR_NOT_FISCAL: result = DescDefines.APP_ERR_GMP3_ECR_NOT_FISCAL; break;
                case Defines.APP_ERR_GMP3_NO_FUNCTION: result = DescDefines.APP_ERR_GMP3_NO_FUNCTION; break;
                case Defines.APP_ERR_GMP3_MALI_KUMULATIF_RAPOR: result = DescDefines.APP_ERR_GMP3_MALI_KUMULATIF_RAPOR; break;
                case Defines.APP_ERR_GMP3_SINEMA_BILET_DESTEGI: result = DescDefines.APP_ERR_GMP3_SINEMA_BILET_DESTEGI; break;
                case Defines.APP_ERR_GMP3_PARAMETRE_HATASI: result = DescDefines.APP_ERR_GMP3_PARAMETRE_HATASI; break;
                case Defines.APP_ERR_GMP3_Z_REQUIRED: result = DescDefines.APP_ERR_GMP3_Z_REQUIRED; break;
                case Defines.APP_ERR_GMP3_UNSUPPORTED: result = DescDefines.APP_ERR_GMP3_UNSUPPORTED; break;
                case Defines.APP_ERR_GMP3_SINEMA_URUN_SAYISI: result = DescDefines.APP_ERR_GMP3_SINEMA_URUN_SAYISI; break;
                case Defines.APP_ERR_GMP3_PAYMENT_CANCELLED: result = DescDefines.APP_ERR_GMP3_PAYMENT_CANCELLED; break;
                case Defines.APP_ERR_GMP3_ITEM_URUN_SAYISI: result = DescDefines.APP_ERR_GMP3_ITEM_URUN_SAYISI; break;
                case Defines.APP_ERR_GMP3_RESOURCE_PROBLEM: result = DescDefines.APP_ERR_GMP3_RESOURCE_PROBLEM; break;
                case Defines.APP_ERR_GMP3_PLU_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_PLU_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_NOT_PROPER_DISCOUNT: result = DescDefines.APP_ERR_GMP3_NOT_PROPER_DISCOUNT; break;
                case Defines.APP_ERR_GMP3_BIRIM_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_BIRIM_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_MIKTAR_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_MIKTAR_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_URUN_ADI_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_URUN_ADI_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_TUTAR_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_TUTAR_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_UNKNOWN_ISLEM_TIPI: result = DescDefines.APP_ERR_GMP3_UNKNOWN_ISLEM_TIPI; break;
                case Defines.APP_ERR_GMP3_VERGI_NOT_AVAILABLE: result = DescDefines.APP_ERR_GMP3_VERGI_NOT_AVAILABLE; break;
                case Defines.APP_ERR_GMP3_ISLEM_NOT_ALLOWED: result = DescDefines.APP_ERR_GMP3_ISLEM_NOT_ALLOWED; break;
                case Defines.APP_ERR_GMP3_CURRENCY_NOT_AVAILABLE: result = DescDefines.APP_ERR_GMP3_CURRENCY_NOT_AVAILABLE; break;
                case Defines.APP_ERR_GMP3_FIS_ITEM_NOT_ALLOWED: result = DescDefines.APP_ERR_GMP3_FIS_ITEM_NOT_ALLOWED; break;
                case Defines.APP_ERR_GMP3_FATURA_PARAMETER_MISSING: result = DescDefines.APP_ERR_GMP3_FATURA_PARAMETER_MISSING; break;
                case Defines.APP_ERR_GMP3_FATURA_TARIHI_MISSING: result = DescDefines.APP_ERR_GMP3_FATURA_TARIHI_MISSING; break;
                case Defines.APP_ERR_GMP3_TUTAR_NOT_REQUIRED: result = DescDefines.APP_ERR_GMP3_TUTAR_NOT_REQUIRED; break;
                case Defines.APP_ERR_GMP3_TUTAR_REQUIRED: result = DescDefines.APP_ERR_GMP3_TUTAR_REQUIRED; break;
                case Defines.APP_ERR_GMP3_INCORRECT_PASSWORD: result = DescDefines.APP_ERR_GMP3_INCORRECT_PASSWORD; break;
                case Defines.APP_ERR_GMP3_INACTIVE_CASHIER_INDEX: result = DescDefines.APP_ERR_GMP3_INACTIVE_CASHIER_INDEX; break;
                case Defines.APP_ERR_GMP3_APPLICATION_NOT_FOUND: result = DescDefines.APP_ERR_GMP3_APPLICATION_NOT_FOUND; break;
                case Defines.APP_ERR_GMP3_UNDEFINED_TAG: result = DescDefines.APP_ERR_GMP3_UNDEFINED_TAG; break;
                case Defines.APP_ERR_GMP3_SAVE_ECR_HEADER: result = DescDefines.APP_ERR_GMP3_SAVE_ECR_HEADER; break;
                case Defines.APP_ERR_GMP3_INVALID_RECIPT_LIMIT: result = DescDefines.APP_ERR_GMP3_INVALID_RECIPT_LIMIT; break;
                case Defines.APP_ERR_GMP3_ADVANCE: result = DescDefines.APP_ERR_GMP3_ADVANCE; break;
                case Defines.APP_ERR_GMP3_PAYMENT: result = DescDefines.APP_ERR_GMP3_PAYMENT; break;
                case Defines.APP_ERR_GMP3_TRANSACTION_IS_ACTIVE: result = DescDefines.APP_ERR_GMP3_TRANSACTION_IS_ACTIVE; break;
                case Defines.APP_ERR_GMP3_FATURA_TYPE_NOT_AVAILABLE: result = DescDefines.APP_ERR_GMP3_FATURA_TYPE_NOT_AVAILABLE; break;
                case Defines.APP_ERR_GMP3_FATURA_INVALID_TCK: result = DescDefines.APP_ERR_GMP3_FATURA_INVALID_TCK; break;
                case Defines.APP_ERR_INVALID_UNIQUE_ID: result = DescDefines.APP_ERR_INVALID_UNIQUE_ID; break;
                case Defines.APP_ERR_GMP3_TICKET_TYPE: result = DescDefines.APP_ERR_GMP3_TICKET_TYPE; break;
                case Defines.APP_ERR_GMP3_SETTINGS: result = DescDefines.APP_ERR_GMP3_SETTINGS; break;
                case Defines.APP_ERR_GMP3_BITMAP: result = DescDefines.APP_ERR_GMP3_BITMAP; break;
                case Defines.APP_ERR_GMP3_FILE: result = DescDefines.APP_ERR_GMP3_FILE; break;
                case Defines.APP_ERR_GMP3_ADMIN_PASSWORD_BLOCKED: result = DescDefines.APP_ERR_GMP3_ADMIN_PASSWORD_BLOCKED; break;
                case Defines.APP_ERR_GMP3_CASHIER_PASSWORD_BLOCKED: result = DescDefines.APP_ERR_GMP3_CASHIER_PASSWORD_BLOCKED; break;
                case Defines.APP_ERR_GMP3_CASHIER_PASSWORD_INCORRECT: result = DescDefines.APP_ERR_GMP3_CASHIER_PASSWORD_INCORRECT; break;
                case Defines.APP_ERR_GMP3_VAS_SUPPORT: result = DescDefines.APP_ERR_GMP3_VAS_SUPPORT; break;
                case Defines.APP_ERR_GMP3_OTOPARK_PARAMETER: result = DescDefines.APP_ERR_GMP3_OTOPARK_PARAMETER; break;
                case Defines.APP_ERR_GMP3_NO_EMPTY_KEY_SLOT: result = DescDefines.APP_ERR_GMP3_NO_EMPTY_KEY_SLOT; break;
                case Defines.DLL_RETCODE_PORT_NOT_OPEN: result = DescDefines.DLL_RETCODE_PORT_NOT_OPEN; break;
                case Defines.DLL_RETCODE_ECR_DATA_ERR: result = DescDefines.DLL_RETCODE_ECR_DATA_ERR; break;
                case Defines.DLL_RETCODE_POS_DATA_ERR: result = DescDefines.DLL_RETCODE_POS_DATA_ERR; break;
                case Defines.DLL_RETCODE_TIMEOUT: result = DescDefines.DLL_RETCODE_TIMEOUT; break;
                case Defines.DLL_RETCODE_DATA_SEND_ERR: result = DescDefines.DLL_RETCODE_DATA_SEND_ERR; break;
                case Defines.DLL_RETCODE_LENGHT_ERR: result = DescDefines.DLL_RETCODE_LENGHT_ERR; break;
                case Defines.DLL_RETCODE_SESSIONID_ERR: result = DescDefines.DLL_RETCODE_SESSIONID_ERR; break;
                case Defines.DLL_RETCODE_DATA_RECV_ERR: result = DescDefines.DLL_RETCODE_DATA_RECV_ERR; break;
                case Defines.DLL_RETCODE_No_ERR: result = DescDefines.DLL_RETCODE_No_ERR; break;
                case Defines.DLL_RETCODE_RECV_EOT: result = DescDefines.DLL_RETCODE_RECV_EOT; break;
                case Defines.DLL_RETCODE_LEN_TOO_LONG: result = DescDefines.DLL_RETCODE_LEN_TOO_LONG; break;
                case Defines.DLL_RETCODE_FAIL: result = DescDefines.DLL_RETCODE_FAIL; break;
                case Defines.DLL_RETCODE_ERROR_STX: result = DescDefines.DLL_RETCODE_ERROR_STX; break;
                case Defines.DLL_RETCODE_ERROR_ETX: result = DescDefines.DLL_RETCODE_ERROR_ETX; break;
                case Defines.DLL_RETCODE_ERROR_CRC: result = DescDefines.DLL_RETCODE_ERROR_CRC; break;
                case Defines.DLL_RETCODE_ERROR_MSGTYPE: result = DescDefines.DLL_RETCODE_ERROR_MSGTYPE; break;
                case Defines.DLL_RETCODE_ERROR_ERR: result = DescDefines.DLL_RETCODE_ERROR_ERR; break;
                case Defines.DLL_RETCODE_ERROR_SID: result = DescDefines.DLL_RETCODE_ERROR_SID; break;
                case Defines.DLL_RETCODE_ERROR_EOT: result = DescDefines.DLL_RETCODE_ERROR_EOT; break;
                case Defines.DLL_RETCODE_STATUS_CODE_ERR: result = DescDefines.DLL_RETCODE_STATUS_CODE_ERR; break;
                case Defines.DLL_RETCODE_LEN_TOO_SHORT: result = DescDefines.DLL_RETCODE_LEN_TOO_SHORT; break;
                case Defines.DLL_RETCODE_DEMO_VERSION: result = DescDefines.DLL_RETCODE_DEMO_VERSION; break;
                case Defines.DLL_RETCODE_FILE_OPEN_ERR: result = DescDefines.DLL_RETCODE_FILE_OPEN_ERR; break;
                case Defines.DLL_RETCODE_KEY_ERROR: result = DescDefines.DLL_RETCODE_KEY_ERROR; break;
                case Defines.DLL_RETCODE_TERMSN_ERROR: result = DescDefines.DLL_RETCODE_TERMSN_ERROR; break;
                case Defines.DLL_RETCODE_ERROR_LRC: result = DescDefines.DLL_RETCODE_ERROR_LRC; break;
                case Defines.DLL_RETCODE_REC_EOT_OK: result = DescDefines.DLL_RETCODE_REC_EOT_OK; break;
                case Defines.DLL_RETCODE_ACK_NOT_RECEIVED: result = DescDefines.DLL_RETCODE_ACK_NOT_RECEIVED; break;
                case Defines.DLL_RETCODE_RECV_BUSY: result = DescDefines.DLL_RETCODE_RECV_BUSY; break;
                case Defines.DLL_RETCODE_RECV_ACK: result = DescDefines.DLL_RETCODE_RECV_ACK; break;
                case Defines.DLL_RETCODE_RECV_NAK: result = DescDefines.DLL_RETCODE_RECV_NAK; break;
                case Defines.DLL_RETCODE_INTERCHAR_TIMEOUT: result = DescDefines.DLL_RETCODE_INTERCHAR_TIMEOUT; break;
                case Defines.DLL_RETCODE_PAIRING_REQUIRED: result = DescDefines.DLL_RETCODE_PAIRING_REQUIRED; break;
                case Defines.DLL_RETCODE_WORG_PING_RETURN: result = DescDefines.DLL_RETCODE_WORG_PING_RETURN; break;
                case Defines.DLL_RETCODE_MEMORY_ERROR: result = DescDefines.DLL_RETCODE_MEMORY_ERROR; break;
                case Defines.DLL_RETCODE_JSON_ERROR: result = DescDefines.DLL_RETCODE_JSON_ERROR; break;
                case Defines.DLL_RETCODE_ECR_VERSION_TOO_OLD: result = DescDefines.DLL_RETCODE_ECR_VERSION_TOO_OLD; break;
                case Defines.DLL_RETCODE_PROCESSING_NUMBER_MISMATCH: result = DescDefines.DLL_RETCODE_PROCESSING_NUMBER_MISMATCH; break;
                case Defines.DLL_RETCODE_DECRYPTION_ERR: result = DescDefines.DLL_RETCODE_DECRYPTION_ERR; break;
                case Defines.DLL_RETCODE_HASH_CALCULATE_ERROR: result = DescDefines.DLL_RETCODE_HASH_CALCULATE_ERROR; break;
                case Defines.DLL_RETCODE_INVALID_STRUCT_SIZE: result = DescDefines.DLL_RETCODE_INVALID_STRUCT_SIZE; break;
                case Defines.APP_ERR_NOT_ALLOWED_AS_GMP3_TRANSACTION_IS_PENDING:result = DescDefines.APP_ERR_NOT_ALLOWED_AS_GMP3_TRANSACTION_IS_PENDING;break;
                case Defines.GMP3_RECEIPT_CAN_NOT_VOID: result = DescDefines.GMP3_RECEIPT_CAN_NOT_VOID; break;
                    
                default: result = "Hata Kodu = " + errorCode.ToString("X2"); break;
            }
            return result;
        }


        public static string DisplayErrorCodeMessage(UInt32 errorCode)
        {
            byte[] TempErrorBuffer = new byte[256];
            string message = "";
            try
            {
                GMPSmartDLL.GetErrorMessage(errorCode, TempErrorBuffer);
                string text = GMP_Tools.SetEncoding(TempErrorBuffer);
                if (!string.IsNullOrEmpty(text))
                {
                    message = "0x" + errorCode.ToString("X2").PadLeft(4, '0') + " : " + text;
                }
            }
            catch
            {
                message = "";
            }
            return message.Trim().Replace("\u0000", "");
        }

    }
}
